apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: b1709267/shop-on-offline:2.1.2
          imagePullPolicy: IfNotPresent
          resources:
           requests:
             memory: "50Mi"
             cpu: "250m"
           limits:
             memory: "200Mi"
             cpu: "250m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - name: react-app
      port: 3000
      targetPort: 3000
